# Generated by Django 5.2.4 on 2025-07-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_answer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
